openapi: 3.0.1
info:
  title: API de consultório
  description: API para controlar médicos e suas especialidades dentro de um consultório.
  version: 0.0.1
  termsOfService: https://mockapi.io
  contact:
    name: Suporte Devs.
    email: contato@example.com
    url: https://mockapi.io
  license:
    name: "Licença GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html

externalDocs:
  description: Documentação burocrática.
  url:  https://mockapi.io
  
servers:
  - url: https://665470911c6af63f4677efbb.mockapi.io
    description: API Teste

paths:
  /especialidades:
    get:
      summary: Recupera todas as especialidades
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Especialidades"
  
    post:
      summary: Cria uma nova especialidade
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Especialidade"

  /especialidades/{id}:
    get:
      summary: Recupera uma entidade pelo ID
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Especialidade"
        404:
          description: Especificação não encontrada
          content:
            application/json:
              example: "Not Found"

    delete:
      summary: Apaga uma entidade pelo ID
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: "File deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Especialidade"
        404:
          description: Especificação não encontrada
          content:
            application/json:
              example: "Not Found"
security:
    - auth: []
components:
  schemas:
    Especialidade:
      type: object
      properties:
        id:
          type: string
        descricao:
          type: string
    
    Especialidades:
      type: array
      items:
        $ref: "#/components/schemas/Especialidade"

  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT